version: "2"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend/
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 4444
      MONGO_URL: "mongodb://mongo/nodeHeadless"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend/
      - "/frontend/node_modules"

  nginx:
    image: "nginx"
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.server.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: "mongo"
    volumes:
      - ./dev/mongo:/data
