version: "2"

services:
  backend:
    image: node:lts
    working_dir: /backend
    volumes:
      - ./backend:/backend/
    depends_on:
      - mongo
      - redis
    command: "npm start"
    environment:
      IS_DEV: "true"
      SERVER_PORT: 4444
      MONGO_URL: "mongodb://mongo/nodeHeadless"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      SESSION_SECRET: "cdc722f09b746bd818f8b6c4d53796e846137a6b13b703d64a9f60ca619d1fa9"

  frontend:
    image: node:lts
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend/
    command: "npm start"

  nginx:
    image: "nginx"
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./dev/nginx/server.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: "mongo"
    volumes:
      - ./dev/mongo:/data

  redis:
    image: "redis"
    volumes:
      - ./dev/redis:/data
