version: "2"

services:
  node:
    build: ./node
    volumes:
      - ./node:/node/
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 4444
      MONGO_URL: "mongodb://mongo/nodeHeadless"

  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.server.conf:/etc/nginx/conf.d/default.conf
      - ./client:/client

  mongo:
    image: "mongo"
    volumes:
      - ./dev/mongo:/data
